LapworthAaron/Football_stats

- assets/js/script.js
JS code to create the League table dynamically from the api call
The league table <section> in the <main> will need to have an id of `leagueTable`
The update button on the league filter banner will need an id of `updateBtn`
> League table js

- assets/css/style.css
- index.html
Screen shared to combine TOM/ADIL HTML&CSS
Single HTML and CSS file
> single page merge done locally, one HTML and CSS to work from

- assets/js/script.js
Creating the schedule code in JS to auto populate the from the api call
> Schedule js

- assets/js/script.js
JS code to call functions on tab clicks and hide/show the relevant html elements for each page. Also sets click listeners for each pages buttons
> tab behaviour and hide_show elements

- assets/css/style.css
- index.html
Hidden the player search and shcedule section to test with js
> Hidden the player search and shcedule section to test with js

- assets/js/script.js
adding missing hideshow function
> adding hideshow function

- index.html
> library change made

- assets/js/script.js
adding in missing argument into function
> added response object added leagueTableContents

- assets/js/script.js
Added JS code to call the player info data from the api and populate it into HTML elements
> player bio section JS

- assets/css/style.css
- assets/js/script.js
- index.html
- added search input for Player Search
- styled all dropdown elements to bring into page theme
- refactored nav title as clickable btn
- added JS for page title on click to refresh page - i.e. return to 'landing page state'
> Dropdown styling + 

- assets/js/script.js
- fixture dynamic HTML JS changed to generate divs for styling
> Fixture Section - JS dynamic HTML

- assets/css/style.css
- assets/js/script.js
- index.html
> added buttons and styled the image on player info

- assets/js/script.js
adjusted dynamic HTML creation with divs and classes for styling
> Playersearch JS dynamic HTML div adjuststs

- assets/js/script.js
adding localStorage functionality for the player search page.
displays buttons and clears them when requested
> Localstorage buttons

- assets/css/style.css
- assets/js/script.js
CSS tweaks to bring sections into theme, tables to display full viewport width
> CSS tweaks for page theme

- assets/css/style.css
missed changing some css from id to class
> missed styling added in

- assets/css/style.css
adding media queries to the league table to hide columns as the screen shrinks
> Media queries league table

- assets/js/script.js
- index.html
- took Adil's HTML template and request to amend existing JS to dynamically generate Player Search results in matching format
- refactored playerHtml function to use template literals syntax, to dynamically create HTML in requested format
- removed instagram FA icon element as API provided Twitter only social media
-- tested changes,
> JS for Adil

- assets/css/style.css
- assets/js/script.js
Split out logic written Saturday into two distinct functions
- API call and HTML gen for Fixtures + creating YouTube btns with fixture specific data tags
- YouTube btn API call logic using fixture specific data to build call + Modal show and population with 3 YT results 
Some simple styling of modal divs containing YT responses
> Yt fixture func split

- assets/css/style.css
> pointer bugfix, table styling alignment with league

- assets/js/script.js
changed dynamic HTML generated <h4> tag to <p> tag
> <h4> to <p> tag

- README.md
- assets/css/style.css
1.Created The ReadMe File.
2. Included The following Sections in ReadMe:
2.1. The Group (Group Name/Members) , Technical Acceptance Criteria, API Servers Used, User Interface Design (Color Palette , Font). 
3. Will add the screenshots after the final touches are done.
4.Changed the var of brand color from green to black in CSS as green was not being used in the website.
> Wrote the ReadMe file

- README.md
- assets/css/style.css
- assets/js/script.js
- index.html
1. Reduced the space between Img and Bio to group them together.
2. Restyled Clear Search Button
3. Drop-Shadow and border to Player Image
4. Changed header size of PlayerInfo and PlayerBio as <p> was looking too small.
5. Added background color to PlayerInfo so it's readable because of the background Image.
6. Set the background Image to repeat so there's no empty space in the player Search Page and it looks proportionate.
7. Aligned the text to be centrally aligned under the player Image.
> Polished the Player Search Page Styling

- assets/css/style.css
- assets/js/script.js
adding styling for the player search validation modals
> styling player search modal

- README.md
- assets/css/style.css
- assets/js/script.js
date fix on fixtures
future fixture to show vs instead of scores
add url to readme
change player description to p tag
change player description styling
keep league table and fixtures
restyle recent search buttons
> js fixes and more css

- assets/js/script.js
> icon src fix

- index.html
missing div in the landing page section added
> added in missing close div tag

- assets/css/style.css
- assets/js/script.js
Changed background styling 
Created Flexboxes within Grid
changed Grid margin
amended JS to break out player Info into divs and h/p tags
> player search styling

- assets/js/script.js
- index.html
PR to allow searched players to persist when you leave the player search page and come back, this helps reduce API calls
> player searchin persist added

- assets/css/style.css
- assets/js/script.js
used .split('.') to break up API data response for player biography into an array of scentences
added for loop to <p> tag each scentence in the array and display a limited number
styled the new <p> tags for player search section
> Player search p split

- README.md
- assets/css/style.css
- index.html
1. Changed the Layout of the grid and redefined grids for Recent Search Header, Player Img, Player Bio,  as flex for mobile and tablets
2. Re-defined the width of the buttons for tablets
3. For tablets and mobiles of a width of 600px: Redefined the Section and made Recent Searches appear before the playerImg, Bio, and info for a better User Experience.
4. For mobiles, hide the recent search aside class.
5. Designed Tables for ReadMe File
6. Formatted some of the CSS so it's easily readable.
> Media query player search

- assets/js/script.js
- index.html
PR to do the following:
- populate alt tags for images
- cope with nulls in playerInfo
- remove "Promotion - " from premier league table
> alt names for img and nulls in playerinfo

- assets/css/style.css
- assets/js/script.js
- JS addition to both League and Player Search logic to generate a header for both sections to match Fixtures section
- Headers styled for both
- All 3 sections now headed with same styling
> League heading

- assets/js/script.js
- index.html
- player title bug fix
- YT icon bug fix
> Player title bug YT bug

- assets/css/style.css
- assets/js/script.js
rebuilt the structure of the CSS
used variables for all colours
removed not needed properties commented out
removed excessive empty lines
> Css file formatting

- README.md
Secondary Bulletpoint buttons for ReadMe
> added bullet points to ReadMe
